post/urls.py
from django.conf.urls import url

from .views import *


app_name = 'post'
urlpatterns = [
    url(r'^$', IndexView.as_view(), name="index"),
    url(r'^posts/$', IndexView.as_view(), name="index"),
    url(r'^add/$', AddView.as_view(), name="add_post"),
    url(r'^edit/(?P<pk>[\d]+)/$', EditView.as_view(), name="edit_post"),
    url(r'^posts/in/(?P<category_id>[\d]+)/$', CategoryView.as_view(), name="category"),
    url(r'^search/$', SearchView.as_view(), name="search"),
    url(r'^posts/by/(?P<username>[\w]+)/$', AuthorView.as_view(), name="user_posts"),
]

urls.py
import django
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
admin.autodiscover()


from post.views import *
from people.views import *



# handler404 = custom404

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
]

urlpatterns += [
    url(r'^login/$', auth_views.LoginView.as_view(),
        {'template_name': 'login.html.django'}, name="login"),
    url(r'^register/$', RegistrationView.as_view(), name="register"),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name="logout"),

    url(r'^', include('post.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

people/models.py
from django.db import models

# Create your models here.

post/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone


class Category(models.Model):
    name = models.CharField(_('name'),  max_length=200, help_text=_('Name of category'))

    def __unicode__(self):
        return self.name

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(_('title'), max_length=200, help_text=_('Title'))
    text = models.TextField(_('text'), help_text=_('Full text'))
    is_published = models.BooleanField(_('published'), default=True,
        help_text=_('Designates whether post is published'))
    publish_date = models.DateTimeField(_('date published'), default=timezone.now)
    author = models.ForeignKey(User, related_name='author')
    category = models.ForeignKey(Category, related_name='category')

    def get_absolute_url(self):
        return '/'

    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _('post')
        verbose_name_plural = _('posts')

people/views.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.views.generic.edit import CreateView
from django.core.urlresolvers import reverse


class RegistrationView(CreateView):
    template_name = 'register.html.django'
    model = User
    form_class = UserCreationForm

    def get_success_url(self):
        return reverse('login')

post/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import TemplateView
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import redirect
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.db.models import Sum, Q
from datetime import date
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic import ListView
from django.contrib.auth.models import User

from post.models import Post, Category


class IndexView(TemplateView):
    template_name = 'post/post_list.html'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['post_list'] = Post.objects.filter(is_published=True).order_by('-publish_date')[0:3]
        context['category_list'] = Category.objects.order_by('name')
        return context


class AddView(CreateView):
    template_name = 'post/add_post.html'
    model = Post
    fields = ['title', 'text', 'category']

    def form_valid(self, form):
        """
        Current user is the author of the post
        """
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.save()
        return super(AddView, self).form_valid(form)

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(AddView, self).dispatch(*args, **kwargs)


class EditView(UpdateView):
    template_name = 'post/add_post.html'
    model = Post
    fields = ['title', 'text', 'category']

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(EditView, self).dispatch(*args, **kwargs)


class AuthorView(TemplateView):
    template_name = 'post/post_list.html'

    def get_context_data(self, **kwargs):
        context = super(AuthorView, self).get_context_data(**kwargs)
        username = self.kwargs.get('username', '')
        get_object_or_404(User, username=username)
        context['post_list'] = Post.objects.filter(is_published=True, author__username=username).order_by('-publish_date')[:3]
        context['category_list'] = Category.objects.order_by('name')
        context['author_username'] = username
        return context


class CategoryView(TemplateView):
    template_name = 'post/post_list.html'

    def get_context_data(self, **kwargs):
        context = super(CategoryView, self).get_context_data(**kwargs)
        category_id = self.kwargs.get('category_id', '')
        get_object_or_404(Category, category__id=category_id)
        context['category_name'] = Category.objects.filter(category__id=category_id).first()
        context['post_list'] = Post.objects.filter(category__id=category_id).order_by('-publish_date')[:3]
        context['category_list'] = Category.objects.order_by('name')
        return context


class SearchView(ListView):
    template_name = 'post/post_list.html'

    def get_context_data(self, **kwargs):
        context = super(SearchView, self).get_context_data(**kwargs)
        context['search_term'] = self.request.GET.get('q', '')
        context['category_list'] = Category.objects.order_by('name')
        return context

    def get_queryset(self):
        search_term = self.request.GET.get('q', '')
        terms = search_term.split(' ')
        q = Q()
        for term in terms:
            q = (q |
                 Q(title__icontains=term) |
                 Q(text__icontains=term) |
                 Q(category__name__icontains=term)
            )
        return Post.objects.filter(q)[:3]

post/templates/post/add_post.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block head_title %}Add new post to The Collective{% endblock %}


{% block extra_head %}
    <link rel="stylesheet" href="{% static "post/css/post.css" %}">
{% endblock extra_head %}

{% block extra_navigation %}
  {% include 'post/blocks/extra_navigation.html' %}
{% endblock extra_navigation %}

{% block content %}

      <div class="row">

        <div class="col-sm-8 blog-main">
            <form method="post" action="" class="form-signin">{% csrf_token %}
                {{ form|crispy }}
                <div>
                <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </form>
        </div><!-- /.blog-main -->

        <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
        </div><!-- /.blog-sidebar -->

      </div><!-- /.row -->

{% endblock content %}

post/templates/post/blocks/category_list.html
{% if category_list %}
  <ol class="list-unstyled">
    {% for category in category_list %}
        <li><a href="{% url 'post:category' category.id %}">{{ category.name }}</a></li>
    {% endfor %}
  </ol>
{% else %}
    No categories yet
{% endif %}

post/templates/post/blocks/extra_navigation.html
<nav class="blog-nav nav navbar-nav">
  <a class="blog-nav-item" href="{% url 'post:add_post' %}">Add post</a>
</nav>
<form class="blog-nav-form navbar-form navbar-left" action="{% url 'post:search' %}">
  <input type="text" class="form-control" placeholder="Enter title, text or category" name="q">
  <button type="submit" class="btn btn-default">Search</button>
</form>

post/templates/post/blocks/login_or_register.html
<h4>Welcome</h4>
{% if user.is_authenticated %}
    Nice to see you, {{ user.username }}!
{% else %}
<p>In order to create a post, you should
    <a href="{% url 'login' %}">login</a> or
    <a href="{% url 'register' %}">register</a>
</p>
{% endif %}

post/templates/post/blocks/post_item.html
{% if post_list %}
  {% for post in post_list %}
  <div class="blog-post">
      <h2 class="blog-post-title">{{ post.title }}</h2>
      <p class="blog-post-meta">
          <span class="blog-post-meta">
          {% if post.author == user %}
          <a href="{% url 'post:edit_post' post.id %}">Edit</a>
          {% endif %}
          </span>
          {{ post.publish_date }} by <a href="{% url 'post:user_posts' post.author.username %}">{{ post.author }}</a>
      </p>
      <p>{{ post.text }}</p>
      <p class="blog-post-meta">
          Posted in <span><a href="{% url 'post:category' post.category.id %}">&quot;{{ post.category }}&quot;</a></span>
      </p>
  </div><!-- /.blog-post -->
  {% endfor %}
{% else %}
  <p>No posts yet.
  {% if user.is_authenticated %}
      <a href="{% url 'post:add_post' %}">Add a post</a></p>
  {% endif %}
{% endif %}

post/templates/post/post_list.html
{% extends "base.html" %}


{% block head_title %}
  {% if category_name %}
      &quot;{{ category_name|default_if_none:"" }}&quot; category on
  {% elif author_username %}
      &quot;{{ author_username|default_if_none:"" }}&quot;s posts on
  {% elif search_term %}
      search for &quot;{{ search_term|default_if_none:"" }}&quot; -
  {% endif %}The Collective
{% endblock head_title %}


{% block extra_navigation %}
  {% include 'post/blocks/extra_navigation.html' %}
{% endblock extra_navigation %}


{% block header_description %}
  {% if category_name %}
      <p class="lead blog-description">Posts in &quot;{{ category_name|default_if_none:"" }}&quot;</p>
  {% elif author_username %}
      <p class="lead blog-description">Posts by &quot;{{ author_username|default_if_none:"" }}&quot;</p>
  {% elif search_term %}
      <p class="lead blog-description">Search results for &quot;{{ search_term|default_if_none:"" }}&quot;</p>
  {% endif %}
{% endblock header_description %}


{% block content %}
  <div class="row">
    <div class="col-sm-8 blog-main">
        {% include 'post/blocks/post_item.html' with post_list=post_list %}
    </div><!-- /.blog-main -->

    <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
      <div class="sidebar-module sidebar-module-inset">
        {% include 'post/blocks/login_or_register.html'%}
      </div>
      <div class="sidebar-module">
        <h4>Categories</h4>
        {% include 'post/blocks/category_list.html' with category_list=category_list %}
      </div>
    </div><!-- /.blog-sidebar -->
  </div><!-- /.row -->
{% endblock content %}


{% block post_login_or_register %}
  <h4>Welcome</h4>
  {% if user.is_authenticated %}
      Nice to see you, {{ user.username }}!
  {% else %}
  <p>In order to create a post, you should
      <a href="{% url 'login' %}">login</a> or
      <a href="{% url 'register' %}">register</a>
  </p>
  {% endif %}
{% endblock %}


{% block post_categories %}

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html><html lang="en">
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static "favicon.ico" %}">

    <title>
    {% block head_title %}The Collective{% endblock head_title %}
    </title>

    <!-- Bootstrap core CSS -->
    <link href="{% static "bootstrap/css/bootstrap.css" %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static "post/css/blog.css" %}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="{% static "bootstrap/js/ie-emulation-modes-warning.js" %}"></script>

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static "bootstrap/js/ie10-viewport-bug-workaround.js" %}"></script>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <style type="text/css" id="holderjs-style"></style>

    {% block extra_head %}
    {% endblock extra_head %}
</head>


<body>
  <div class="blog-masthead">
    <div class="container">
      <nav class="blog-nav nav navbar-nav">
        <a class="blog-nav-item" href="/">The collective</a>
      </nav>

      {% block extra_navigation %}
{#      <nav class="blog-nav nav navbar-nav">#}
{#        <a class="blog-nav-item" href="{% url 'post:add_post' %}">Add post</a>#}
{#      </nav>#}
{#      <form class="blog-nav-form navbar-form navbar-left" action="{% url 'post:search' %}">#}
{#        <input type="text" class="form-control" placeholder="Enter title, text or category" name="q">#}
{#        <button type="submit" class="btn btn-default">Search</button>#}
{#      </form>#}
      {% endblock extra_navigation %}

      <nav class="blog-nav nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
        <a class="blog-nav-item" href="{% url 'logout' %}">Logout</a>
        {% else %}
        <a class="blog-nav-item" href="{% url 'register' %}">Register</a>
        <a class="blog-nav-item" href="{% url 'login' %}">Login</a>
        {% endif %}
      </nav>
    </div>
  </div>


    <div class="container">
        <div class="blog-header">
            <h1 class="blog-title">The Collective</h1>
            {% block header_description %}
{#            <p class="lead blog-description">Simple and straight-forward collective blog.</p>#}
            {% endblock header_description %}
        </div>

          {% block content %}

          {% endblock content %}
    </div><!-- /.container -->

  {% block footer %}
  {% endblock footer %}

  <div class="blog-footer">
    <p>Blog template built for <a href="http://getbootstrap.com/">Bootstrap</a> by <a href="https://twitter.com/mdo">@mdo</a>.</p>
    <p>
      <a href="#">Back to top</a>
    </p>
  </div>

<!-- Les scripts
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="{{STATIC_URL}}lib/jquery-1.10.2.min.js"><\/script>')</script>
<script src="{{STATIC_URL}}bootstrap/js/bootstrap.min.js"></script>

{% block extra_scripts %}
{% endblock extra_scripts %}
</body>
</html>

templates/example/blog.html
      <div class="row">

        <div class="col-sm-8 blog-main">

          <div class="blog-post">
            <h2 class="blog-post-title">Sample blog post</h2>
            <p class="blog-post-meta">January 1, 2014 by <a href="#">Mark</a></p>

            <p>This blog post shows a few different types of content that's supported and styled with Bootstrap. Basic typography, images, and code are all supported.</p>
            <hr>
            <p>Cum sociis natoque penatibus et magnis <a href="#">dis parturient montes</a>, nascetur ridiculus mus. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Sed posuere consectetur est at lobortis. Cras mattis consectetur purus sit amet fermentum.</p>
            <blockquote>
              <p>Curabitur blandit tempus porttitor. <strong>Nullam quis risus eget urna mollis</strong> ornare vel eu leo. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
            </blockquote>
            <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
            <h2>Heading</h2>
            <p>Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros.</p>
            <h3>Sub-heading</h3>
            <p>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>
            <pre><code>Example code block</code></pre>
            <p>Aenean lacinia bibendum nulla sed consectetur. Etiam porta sem malesuada magna mollis euismod. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa.</p>
            <h3>Sub-heading</h3>
            <p>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean lacinia bibendum nulla sed consectetur. Etiam porta sem malesuada magna mollis euismod. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
            <ul>
              <li>Praesent commodo cursus magna, vel scelerisque nisl consectetur et.</li>
              <li>Donec id elit non mi porta gravida at eget metus.</li>
              <li>Nulla vitae elit libero, a pharetra augue.</li>
            </ul>
            <p>Donec ullamcorper nulla non metus auctor fringilla. Nulla vitae elit libero, a pharetra augue.</p>
            <ol>
              <li>Vestibulum id ligula porta felis euismod semper.</li>
              <li>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</li>
              <li>Maecenas sed diam eget risus varius blandit sit amet non magna.</li>
            </ol>
            <p>Cras mattis consectetur purus sit amet fermentum. Sed posuere consectetur est at lobortis.</p>
          </div><!-- /.blog-post -->

          <div class="blog-post">
            <h2 class="blog-post-title">Another blog post</h2>
            <p class="blog-post-meta">December 23, 2013 by <a href="#">Jacob</a></p>

            <p>Cum sociis natoque penatibus et magnis <a href="#">dis parturient montes</a>, nascetur ridiculus mus. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Sed posuere consectetur est at lobortis. Cras mattis consectetur purus sit amet fermentum.</p>
            <blockquote>
              <p>Curabitur blandit tempus porttitor. <strong>Nullam quis risus eget urna mollis</strong> ornare vel eu leo. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
            </blockquote>
            <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
            <p>Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros.</p>
          </div><!-- /.blog-post -->

          <div class="blog-post">
            <h2 class="blog-post-title">New feature</h2>
            <p class="blog-post-meta">December 14, 2013 by <a href="#">Chris</a></p>

            <p>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean lacinia bibendum nulla sed consectetur. Etiam porta sem malesuada magna mollis euismod. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
            <ul>
              <li>Praesent commodo cursus magna, vel scelerisque nisl consectetur et.</li>
              <li>Donec id elit non mi porta gravida at eget metus.</li>
              <li>Nulla vitae elit libero, a pharetra augue.</li>
            </ul>
            <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
            <p>Donec ullamcorper nulla non metus auctor fringilla. Nulla vitae elit libero, a pharetra augue.</p>
          </div><!-- /.blog-post -->

          <ul class="pager">
            <li><a href="#">Previous</a></li>
            <li><a href="#">Next</a></li>
          </ul>

        </div><!-- /.blog-main -->

        <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
          <div class="sidebar-module sidebar-module-inset">
            <h4>About</h4>
            <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
          </div>
          <div class="sidebar-module">
            <h4>Archives</h4>
            <ol class="list-unstyled">
              <li><a href="#">March 2014</a></li>
              <li><a href="#">February 2014</a></li>
              <li><a href="#">January 2014</a></li>
              <li><a href="#">December 2013</a></li>
              <li><a href="#">November 2013</a></li>
              <li><a href="#">October 2013</a></li>
              <li><a href="#">September 2013</a></li>
              <li><a href="#">August 2013</a></li>
              <li><a href="#">July 2013</a></li>
              <li><a href="#">June 2013</a></li>
              <li><a href="#">May 2013</a></li>
              <li><a href="#">April 2013</a></li>
            </ol>
          </div>
          <div class="sidebar-module">
            <h4>Elsewhere</h4>
            <ol class="list-unstyled">
              <li><a href="#">GitHub</a></li>
              <li><a href="#">Twitter</a></li>
              <li><a href="#">Facebook</a></li>
            </ol>
          </div>
        </div><!-- /.blog-sidebar -->

      </div><!-- /.row -->